// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFxyd-m5sxTS9k5uD_NsEBr-BkO0adPoc',
    appId: '1:369236225130:web:3043f1a614c5f41071ae13',
    messagingSenderId: '369236225130',
    projectId: 'spkproject-3df9a',
    authDomain: 'spkproject-3df9a.firebaseapp.com',
    storageBucket: 'spkproject-3df9a.appspot.com',
    measurementId: 'G-TXXEXX2QDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0-3VDkhQGTf33h02SNCpSVFIrNmgDrVw',
    appId: '1:369236225130:android:d72029e7d0b4021571ae13',
    messagingSenderId: '369236225130',
    projectId: 'spkproject-3df9a',
    storageBucket: 'spkproject-3df9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEoNxxg1Th-0TfGyySERXsCiA6YK0HGgQ',
    appId: '1:369236225130:ios:fd96ca54587e0d9e71ae13',
    messagingSenderId: '369236225130',
    projectId: 'spkproject-3df9a',
    storageBucket: 'spkproject-3df9a.appspot.com',
    iosClientId: '369236225130-q3tqmspakpsdga0n91su3lr4a33irku8.apps.googleusercontent.com',
    iosBundleId: 'com.example.spkApp',
  );
}
